version: '3'

services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    env_file:
      - .env
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 5s

  wordpress:
    build: requirements/wordpress
    image: wordpress
    env_file:
      - .env
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: requirements/nginx
    image: nginx
    env_file:
      - .env
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - wordpress

networks:
  inception:

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/lorobert/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/lorobert/data/wordpress
      o: bind