version: '3'

services:
  mariadb:
    build: requirements/mariadb
    env_file:
      - .env
    container_name: mariadb
    networks:
      - inception
    expose:
      - 3306
    restart: unless-stopped
  wordpress:
    build: requirements/wordpress
    env_file:
      - .env
    container_name: wordpress
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      - mariadb
  nginx:
    build: requirements/nginx
    env_file:
      - .env
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - wordpress

networks:
  inception: